'use client';

import React from 'react';
import { Users, TrendingUp, Award, DollarSign } from 'lucide-react';

export default function AgentPortalView() {
    // 프레젠테이션용 가짜(Mock) 데이터
    const myMerchants = [
        { id: '1', name: 'Go Tambayan Inc.', volume: 155000, commission: 1550, status: 'Active' },
        { id: '2', name: 'K-Mart Manila', volume: 82000, commission: 820, status: 'Active' },
        { id: '3', name: 'Cebu Resort Hotel', volume: 450000, commission: 4500, status: 'Active' },
    ];

    return (
        <div className="space-y-6">
            <div className="flex justify-between items-center">
                <div>
                    <h2 className="text-2xl font-bold text-gray-800">Agent Partner Portal</h2>
                    <p className="text-gray-500">Welcome back, Juan Dela Cruz (Agent ID: AGT-2026-001)</p>
                </div>
                <div className="bg-purple-50 text-purple-700 px-4 py-2 rounded-lg font-bold border border-purple-100 flex items-center gap-2">
                    <Award className="w-5 h-5" /> Top Tier Agent
                </div>
            </div>

            {/* 실적 요약 카드 */}
            <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
                <div className="bg-gradient-to-br from-purple-600 to-indigo-600 p-6 rounded-2xl text-white shadow-lg">
                    <p className="text-purple-100 font-medium mb-1">Total Commission (This Month)</p>
                    <h3 className="text-3xl font-bold">₱ 6,870.00</h3>
                    <p className="text-sm text-purple-200 mt-2 flex items-center gap-1">Available to withdraw</p>
                </div>
                <div className="bg-white p-6 rounded-2xl border border-gray-100 shadow-sm">
                    <p className="text-gray-500 font-medium mb-1">Active Merchants</p>
                    <h3 className="text-3xl font-bold text-gray-800">12</h3>
                    <p className="text-sm text-gray-400 mt-2">+2 new this week</p>
                </div>
                <div className="bg-white p-6 rounded-2xl border border-gray-100 shadow-sm">
                    <p className="text-gray-500 font-medium mb-1">Total Merchant Volume</p>
                    <h3 className="text-3xl font-bold text-gray-800">₱ 687,000.00</h3>
                    <p className="text-sm text-gray-400 mt-2">Generated by your clients</p>
                </div>
            </div>

            {/* 내가 유치한 가맹점 리스트 */}
            <div className="bg-white rounded-xl shadow-sm border border-gray-100 overflow-hidden">
                <div className="px-6 py-4 border-b border-gray-100 bg-gray-50 flex items-center gap-2">
                    <Users className="w-5 h-5 text-gray-500" />
                    <h3 className="font-bold text-gray-800">My Merchants Performance</h3>
                </div>
                <table className="w-full text-left text-sm">
                    <thead className="bg-white border-b border-gray-100">
                        <tr>
                            <th className="px-6 py-4 text-gray-500 font-semibold">Merchant Name</th>
                            <th className="px-6 py-4 text-gray-500 font-semibold">Monthly Volume</th>
                            <th className="px-6 py-4 text-purple-600 font-semibold">My Commission (1%)</th>
                            <th className="px-6 py-4 text-gray-500 font-semibold">Status</th>
                        </tr>
                    </thead>
                    <tbody className="divide-y divide-gray-50">
                        {myMerchants.map((m) => (
                            <tr key={m.id} className="hover:bg-gray-50">
                                <td className="px-6 py-4 font-bold text-gray-700">{m.name}</td>
                                <td className="px-6 py-4 font-medium">₱ {m.volume.toLocaleString()}</td>
                                <td className="px-6 py-4 font-bold text-purple-600">₱ {m.commission.toLocaleString()}</td>
                                <td className="px-6 py-4">
                                    <span className="bg-green-100 text-green-700 px-2.5 py-1 rounded-full text-xs font-bold">
                                        {m.status}
                                    </span>
                                </td>
                            </tr>
                        ))}
                    </tbody>
                </table>
            </div>
        </div>
    );
}